/* Action Contstants those will be listened by the Reducer and SAGAs */

const GET_CATEGORIES = 'GET_CATEGORIES';
const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

const ADD_CATEGORY = 'ADD_CATEGORY';
const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export {GET_CATEGORIES, GET_CATEGORIES_SUCCESS, GET_CATEGORIES_FAILED, ADD_CATEGORY,ADD_CATEGORY_SUCCESS}
